import { chmod, lstat, mkdir, open, readFile, rename, unlink } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

export const DEFAULT_TARGET = 'https://grafana-mfa.nersc.gov/';
export const DEFAULT_REFRESH_COOKIES = ['grafana_session', 'grafana_session_expiry'];

export class CliError extends Error {
  constructor(message, exitCode = 1) {
    super(message);
    this.name = 'CliError';
    this.exitCode = exitCode;
  }
}

export class AuthenticationRequiredError extends CliError {
  constructor(message) {
    super(message, 2);
    this.name = 'AuthenticationRequiredError';
  }
}

export function parseDuration(value) {
  const match = /^(\d+)(ms|s|m)?$/.exec(String(value));
  if (!match) {
    throw new CliError(`Invalid duration: ${value}`);
  }

  const amount = Number(match[1]);
  const multiplier = { ms: 1, s: 1_000, m: 60_000 }[match[2] ?? 'ms'];
  return amount * multiplier;
}

export function normalizeHttpsUrl(value, label = 'URL') {
  let url;
  try {
    url = new URL(value);
  } catch {
    throw new CliError(`Invalid ${label}: ${value}`);
  }

  if (url.protocol !== 'https:') {
    throw new CliError(`${label} must use HTTPS: ${value}`);
  }
  url.hash = '';
  return url;
}

export function resolveFetchUrl(target, value) {
  const url = new URL(value, target);
  if (url.origin !== target.origin) {
    throw new CliError(
      `Refusing to send browser credentials to ${url.origin}; expected ${target.origin}`,
    );
  }
  return url;
}

export function parseHeader(value) {
  const separator = value.indexOf(':');
  if (separator < 1) {
    throw new CliError(`Invalid header (expected "Name: value"): ${value}`);
  }
  return [value.slice(0, separator).trim(), value.slice(separator + 1).trim()];
}

export function cookieHeader(cookies) {
  return cookies.map(({ name, value }) => `${name}=${value}`).join('; ');
}

export function toNetscapeCookieJar(cookies) {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by headless-mfa. Treat this file as a secret.',
  ];

  for (const cookie of cookies) {
    const domain = cookie.httpOnly ? `#HttpOnly_${cookie.domain}` : cookie.domain;
    const includeSubdomains = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expires = cookie.expires > 0 ? Math.floor(cookie.expires) : 0;
    lines.push(
      [
        domain,
        includeSubdomains,
        cookie.path,
        secure,
        expires,
        cookie.name,
        cookie.value,
      ].join('\t'),
    );
  }

  return `${lines.join('\n')}\n`;
}

export function decodeJwtMetadata(value) {
  const token = value.replace(/^Bearer\s+/i, '');
  const segments = token.split('.');
  if (segments.length !== 3) return undefined;

  try {
    const payload = JSON.parse(Buffer.from(segments[1], 'base64url').toString('utf8'));
    return {
      issuer: payload.iss,
      audience: payload.aud,
      subject: payload.sub,
      issuedAt: epochToIso(payload.iat),
      expiresAt: epochToIso(payload.exp),
    };
  } catch {
    return undefined;
  }
}

function epochToIso(value) {
  return Number.isFinite(value) ? new Date(value * 1_000).toISOString() : undefined;
}

export function suspectedStorageCredentials(entries) {
  const credentialKey = /(access|auth|bearer|credential|jwt|session|token)/i;
  return entries.filter(({ key }) => credentialKey.test(key));
}

export function uniqueAuthorizationHeaders(values) {
  return [...new Set(values.filter((value) => /^(Bearer|Basic)\s+\S+/i.test(value)))];
}

export function redactValue(value, showSecrets = false) {
  if (showSecrets) return value;
  if (!value) return '';
  if (value.length <= 8) return `<redacted:${value.length}>`;
  return `${value.slice(0, 4)}...${value.slice(-4)} <redacted:${value.length}>`;
}

export function credentialOutput(bundle, format, name) {
  const cookies = name ? bundle.cookies.filter((cookie) => cookie.name === name) : bundle.cookies;
  const storage = name
    ? bundle.storage.filter((entry) => entry.key === name)
    : suspectedStorageCredentials(bundle.storage);
  const authorization = name ? [] : uniqueAuthorizationHeaders(bundle.authorization);

  if (name && cookies.length === 0 && storage.length === 0) {
    throw new CliError(`No cookie or browser-storage credential named ${name} was found`, 3);
  }

  if (format === 'json') {
    return `${JSON.stringify({ cookies, authorization, storage }, null, 2)}\n`;
  }

  if (format === 'netscape') {
    if (cookies.length === 0) throw new CliError('No cookies were found for the target URL', 3);
    return toNetscapeCookieJar(cookies);
  }

  if (format === 'value') {
    const values = [
      ...cookies.map((cookie) => cookie.value),
      ...authorization.map((value) => value.replace(/^\S+\s+/, '')),
      ...storage.map((entry) => entry.value),
    ];
    if (values.length !== 1) {
      throw new CliError(
        `Expected exactly one credential but found ${values.length}; use --name or --format json`,
        3,
      );
    }
    return `${values[0]}\n`;
  }

  if (format !== 'header') throw new CliError(`Unknown token format: ${format}`);

  const lines = [];
  if (cookies.length > 0) lines.push(`Cookie: ${cookieHeader(cookies)}`);
  lines.push(...authorization.map((value) => `Authorization: ${value}`));
  if (lines.length === 0 && storage.length > 0) {
    throw new CliError(
      'A possible credential exists only in browser storage; use --format json or the fetch command',
      3,
    );
  }
  if (lines.length === 0) throw new CliError('No credential was found for the target URL', 3);
  return `${lines.join('\n')}\n`;
}

export async function ensurePrivateDirectory(path) {
  await mkdir(path, { recursive: true, mode: 0o700 });
  await chmod(path, 0o700);
}

export async function secureWrite(path, data) {
  const absolute = resolve(path);
  await mkdir(dirname(absolute), { recursive: true, mode: 0o700 });

  try {
    const stat = await lstat(absolute);
    if (stat.isSymbolicLink()) {
      throw new CliError(`Refusing to replace symbolic link: ${absolute}`);
    }
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }

  const temporary = `${absolute}.tmp-${process.pid}-${Date.now()}`;
  let handle;
  try {
    handle = await open(temporary, 'wx', 0o600);
    await handle.writeFile(data);
    await handle.close();
    handle = undefined;
    await chmod(temporary, 0o600);
    await rename(temporary, absolute);
    await chmod(absolute, 0o600);
  } catch (error) {
    if (handle) await handle.close().catch(() => {});
    await unlink(temporary).catch(() => {});
    throw error;
  }
}

export async function readJsonIfPresent(path) {
  try {
    return JSON.parse(await readFile(path, 'utf8'));
  } catch (error) {
    if (error.code === 'ENOENT') return undefined;
    throw new CliError(`Cannot read ${path}: ${error.message}`);
  }
}

export async function acquireLock(path) {
  try {
    const handle = await open(path, 'wx', 0o600);
    await handle.writeFile(
      `${JSON.stringify({ pid: process.pid, host: process.env.HOSTNAME, startedAt: new Date().toISOString() })}\n`,
    );
    await handle.close();
  } catch (error) {
    if (error.code === 'EEXIST') {
      let owner = '';
      try {
        owner = (await readFile(path, 'utf8')).trim();
      } catch {
        // The existence of the lock is enough to reject concurrent use.
      }
      throw new CliError(
        `Browser profile is already in use${owner ? ` (${owner})` : ''}. Remove ${path} only if no headless-mfa process is running.`,
        4,
      );
    }
    throw error;
  }

  let released = false;
  return async () => {
    if (released) return;
    released = true;
    try {
      await unlink(path);
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
  };
}
